/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package accelizea_accelerator;

import invalidPackageName.ApiException;
import io.swagger.client.model.InlineResponse2004;
import java.io.File;
import io.swagger.client.model.InlineResponse2003;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProcessApi
 */
public class ProcessApiTest {

    private final ProcessApi api = new ProcessApi();

    
    /**
     * /v1.0/process/
     *
     * Create a new process instance.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processCreateTest() throws ApiException {
        String _configuration = null;
        String parameters = null;
        File datafile = null;
        // InlineResponse2004 response = api.processCreate(_configuration, parameters, datafile);

        // TODO: test validations
    }
    
    /**
     * /v1.0/process/
     *
     * Returns a list of all process instance requested in the system.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processListTest() throws ApiException {
        Integer page = null;
        // InlineResponse2003 response = api.processList(page);

        // TODO: test validations
    }
    
    /**
     * /v1.0/process/{id}/
     *
     * Return the given process instance.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processReadTest() throws ApiException {
        Integer id = null;
        // InlineResponse2004 response = api.processRead(id);

        // TODO: test validations
    }
    
}
