import os

from acceleratorAPI import logger
from acceleratorAPI.utilities import check_url
from acceleratorAPI.csp import CSPGenericClass as _CSPGenericClass
import openstack


class OpenStackClass(_CSPGenericClass):

    def __init__(self, provider, config_parser, **kwargs):
        self.provider = provider
        project_id = _CSPGenericClass.get_from_args('project_id', **kwargs)
        auth_url = _CSPGenericClass.get_from_args('auth_url', **kwargs)
        interface = _CSPGenericClass.get_from_args('interface', **kwargs)
        super(OpenStackClass, self).__init__(config_parser, **kwargs)
        self.project_id = self.get_from_config('csp', 'project_id', overwrite=project_id)
        if self.project_id is None:
            raise Exception("No 'project_id' field has been specified for %s" % self.provider)
        self.auth_url = self.get_from_config('csp', 'auth_url', overwrite=auth_url)
        if self.auth_url is None:
            raise Exception("No 'auth_url' field has been specified for %s" % self.provider)
        self.interface = self.get_from_config('csp', 'interface', overwrite=interface)
        if self.interface is None:
            raise Exception("No 'interface' field has been specified for %s" % self.provider)
        self.load_session()
        self.instance = None
        self.config_env = {}

    def __str__(self):
        return ', '.join("%s:%s" % item for item in vars(self).items())

    def load_session(self):
        try:
            self.connection = openstack.connection.Connection(
                region_name=self.region,
                auth=dict(
                    auth_url=self.auth_url,
                    username=self.client_id,
                    password=self.secret_id,
                    project_id=self.project_id
                ),
                compute_api_version='2',
                identity_interface=self.interface
            )
            logger.debug("Connection object created for CSP '%s'", self.provider)
        except Exception:
            logger.exception("Caugth following exception:")
            raise Exception("Could not authenticate to your %s account", self.provider)

    def check_csp_credential(self):
        try:
            self.connection.network.networks()
            return True
        except Exception:
            logger.exception("Failed to authenticate to CSP '%s'.", self.provider)
            return False

    def ssh_key_csp(self):
        logger.debug("Create or check if KeyPair %s exists", self.ssh_key)
        try:
            key_pair = self.connection.compute.find_keypair(self.ssh_key, ignore_missing=True)
            if key_pair:
                # Use existing key
                logger.info("KeyPair '%s' is already existing on %s.", str(key_pair.name), self.provider)
            else:
                # Create key pair
                logger.debug("Create KeyPair '%s'", self.ssh_key)
                key_pair = self.connection.compute.create_keypair(name=self.ssh_key)
                # Save private key locally if not existing
                ssh_key_file = self.create_SSH_key_filename()
                logger.debug("Creating private ssh key file: %s", ssh_key_file)
                with open(ssh_key_file, "w") as text_file:
                    text_file.write(key_pair.private_key)
                os.chmod(ssh_key_file, 0o400)
                logger.debug("Key Content: %s", str(key_pair.private_key))
                logger.info("New SSH Key '%s' has been written in '%s'", ssh_key_file, self.ssh_dir)
            return True
        except Exception:
            logger.exception("Failed to create SSH Key with message:")
            return False

    def security_group_csp(self):
        try:
            logger.debug("Create or check if securitygroup '%s' exists", self.security_group)
            security_group = self.connection.get_security_group(self.security_group)
            if security_group is None:
                security_group = self.connection.create_security_group(
                    self.security_group, "Generated by accelize API", project_id=self.project_id
                )
                logger.info("Created security group: %s", security_group.name)
                # Create Security Group Rules if not provided
            else:
                logger.info("Security group '%s' is already existing on %s.", self.security_group, self.provider)
            # Verify rules associated to security group
            public_ip = _CSPGenericClass.get_host_public_ip()  # Find the host public IP
            # Create rule on SSH
            try:
                self.connection.create_security_group_rule(security_group.id, port_range_min=22, port_range_max=22,
                                                           protocol="tcp", remote_ip_prefix=public_ip,
                                                           remote_group_id=None, direction='ingress',
                                                           ethertype='IPv4', project_id=self.project_id
                                                           )
            except Exception:
                # except openstack.exceptions.HttpException:
                pass
            # Create rule on HTTP
            try:
                self.connection.create_security_group_rule(security_group.id, port_range_min=80, port_range_max=80,
                                                           protocol="tcp", remote_ip_prefix=public_ip,
                                                           remote_group_id=None, direction='ingress',
                                                           ethertype='IPv4', project_id=self.project_id
                                                           )
            except Exception:
                # except openstack.exceptions.HttpException:
                pass
            logger.info("Added in security group '%s': SSH and HTTP for IP %s.", self.security_group, public_ip)
            return True
        except Exception:
            logger.exception("Failed to create securityGroup with message:")
            return False

    def create_instance_csp(self):
        if not self.ssh_key_csp():
            return False
        if not self.security_group_csp():
            return False
        return True

    def set_accelerator_requirements(self, accel_parameters):
        if self.region not in accel_parameters.keys():
            logger.error("Region '%s' is not supported. Available regions are: %s", self.region,
                         ', '.join(accel_parameters.keys()))
            return False
        self.accelerator_name = accel_parameters['accelerator']
        accel_parameters_in_region = accel_parameters[self.region]
        # Get image
        self.imageId = accel_parameters_in_region['image']
        try:
            image = self.connection.compute.find_image(self.imageId)
        except Exception:
            logger.exception("Failed to get image information for CSP '%s': ", self.provider)
            custom_message = "The image " + str(
                self.imageId) + " is not available on your CSP account. Please contact Accelize."
            raise Exception(custom_message)
        logger.debug("Set image '%s' with ID %s", image.name, self.imageId)
        # Get flavor
        flavor_name = accel_parameters_in_region['instancetype']
        try:
            self.instance_type = self.connection.compute.find_flavor(flavor_name).id
        except Exception:
            logger.exception("Failed to get flavor information for CSP '%s': ", self.provider)
            raise Exception((
                                "The flavor %s is not available in your CSP account. "
                                "Please contact you CSP to subscribe to this flavor.") % str(flavor_name))

        logger.debug("Set flavor '%s' with ID %s", flavor_name, self.instance_type)
        return True

    def get_configuration_env(self, **kwargs):
        return self.config_env

    def get_instance_public_ip(self):
        try:
            for address in self.instance.addresses.values()[0]:
                if address['version'] == 4:
                    return str(address['addr'])
            return None
        except Exception:
            return None

    def get_instance_csp(self):
        if self.instance_id is None:
            return False
        try:
            self.instance = self.connection.get_server(self.instance_id)
            logger.debug("Found an instance with ID %s in the following state: %s", self.instance_id,
                         self.instance.status)
            return True
        except Exception:
            logger.error("Could not find an instance with ID %s", self.instance_id)
            return False

    def get_instance_url(self):
        if self.instance is None:
            return None
        public_ip = self.get_instance_public_ip()
        if public_ip is None:
            return None
        return "http://%s" % public_ip

    def wait_instance_ready(self):
        try:
            # Waiting for the instance provisioning
            logger.info("Waiting for the instance provisioning on %s...", self.provider)
            self.instance = self.connection.compute.wait_for_server(self.instance)
            state = self.instance.status
            logger.debug("Instance status: %s", state)
            if state.lower() == "error":
                logger.error("Instance has an invalid status: %s", state)
                self.stop_instance_csp(True)
                return False
            # Waiting for the instance to boot
            self.instance_url = self.get_instance_url()
            logger.info("Instance is now booting...")
            if not check_url(self.instance_url, 1, 72, 5, logger=logger):  # 6 minutes timeout
                logger.error("Timed out while waiting CSP instance to boot.")
                return False
            logger.info("Instance booted!")
            return True
        except Exception:
            try:
                self.get_instance_csp()
                msg = self.instance.fault.message
                logger.error("CSP error message: %s ", msg)
            except Exception:
                pass
            logger.exception("Caught following exception:")
            return False

    def start_new_instance_csp(self):
        try:
            logger.debug("Starting instance")
            self.instance = self.connection.compute.create_server(
                name=self.accelerator_name, image_id=self.imageId, flavor_id=self.instance_type,
                key_name=self.ssh_key, security_groups=[{"name": self.security_group}])
            self.instance_id = self.instance.id
            logger.info("Created instance ID: %s", self.instance_id)
            return self.wait_instance_ready()
        except Exception:
            logger.exception("Caught following exception:")
            return False

    def is_instance_ID_valid(self):
        try:
            if not self.get_instance_csp():
                return False
            logger.info("Using instance ID: %s", self.instance_id)
            return True
        except openstack.compute.ResourceNotFound:
            logger.error("Could not find a instance with ID: %s", self.instance_id)
            return False

    def start_existing_instance_csp(self):
        try:
            if not self.is_instance_ID_valid():
                return False
            state = self.instance.status
            logger.debug("Status of instance ID %s: %s", self.instance_id, state)
            if state.lower() == "active":
                logger.debug("Instance ID %s is already in '%s' state.", self.instance_id, state)
                return True
            self.connection.start_server(self.instance)
            if not self.wait_instance_ready():
                logger.error("Error occurred when waiting instance ID '%s' to be ready.", self.instance_id)
                return False
            return True
        except Exception:
            logger.exception("Caught following starting instance ID %s:", self.instance_id)
            return False

    def start_instance_csp(self):
        if self.instance_id is None:
            ret = self.start_new_instance_csp()
        else:
            ret = self.start_existing_instance_csp()
        if not ret:
            return False
        logger.info("Region: %s", self.region)
        public_ip = self.get_instance_public_ip()
        logger.info("Public IP: %s", public_ip)
        logger.info("Your instance is now up and running")
        return True

    def stop_instance_csp(self, terminate=True):
        try:
            if not self.get_instance_csp():
                return False
            if terminate:
                self.connection.delete_server(self.instance)
                logger.info("Instance ID %s has been terminated", self.instance_id)
            else:
                self.connection.stop_server(self.instance)
                logger.info("Instance ID %s has been stopped", self.instance_id)
            return True
        except Exception:
            logger.exception("Caught following exception:")
            return False
