/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AccelizeAcceleratorWs);
  }
}(this, function(expect, AccelizeAcceleratorWs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AccelizeAcceleratorWs.InlineResponse200Results();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse200Results', function() {
    it('should create an instance of InlineResponse200Results', function() {
      // uncomment below and update the code to test InlineResponse200Results
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be.a(AccelizeAcceleratorWs.InlineResponse200Results);
    });

    it('should have the property datafile (base name: "datafile")', function() {
      // uncomment below and update the code to test the property datafile
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property used (base name: "used")', function() {
      // uncomment below and update the code to test the property used
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property parameters (base name: "parameters")', function() {
      // uncomment below and update the code to test the property parameters
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property inerror (base name: "inerror")', function() {
      // uncomment below and update the code to test the property inerror
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property processedDate (base name: "processed_date")', function() {
      // uncomment below and update the code to test the property processedDate
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property processed (base name: "processed")', function() {
      // uncomment below and update the code to test the property processed
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property provider (base name: "provider")', function() {
      // uncomment below and update the code to test the property provider
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instane = new AccelizeAcceleratorWs.InlineResponse200Results();
      //expect(instance).to.be();
    });

  });

}));
