/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200Results'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse200Results'));
  } else {
    // Browser globals (root is window)
    if (!root.AccelizeAcceleratorWs) {
      root.AccelizeAcceleratorWs = {};
    }
    root.AccelizeAcceleratorWs.InlineResponse200 = factory(root.AccelizeAcceleratorWs.ApiClient, root.AccelizeAcceleratorWs.InlineResponse200Results);
  }
}(this, function(ApiClient, InlineResponse200Results) {
  'use strict';




  /**
   * The InlineResponse200 model module.
   * @module model/InlineResponse200
   * @version 1.0
   */

  /**
   * Constructs a new <code>InlineResponse200</code>.
   * @alias module:model/InlineResponse200
   * @class
   * @param count {Integer} 
   * @param previous {String} 
   * @param results {Array.<module:model/InlineResponse200Results>} 
   * @param next {String} 
   */
  var exports = function(count, previous, results, next) {
    var _this = this;

    _this['count'] = count;
    _this['previous'] = previous;
    _this['results'] = results;
    _this['next'] = next;
  };

  /**
   * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200} obj Optional instance to populate.
   * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Integer');
      }
      if (data.hasOwnProperty('previous')) {
        obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [InlineResponse200Results]);
      }
      if (data.hasOwnProperty('next')) {
        obj['next'] = ApiClient.convertToType(data['next'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Integer} count
   */
  exports.prototype['count'] = undefined;
  /**
   * 
   * @member {String} previous
   */
  exports.prototype['previous'] = undefined;
  /**
   * 
   * @member {Array.<module:model/InlineResponse200Results>} results
   */
  exports.prototype['results'] = undefined;
  /**
   * 
   * @member {String} next
   */
  exports.prototype['next'] = undefined;



  return exports;
}));


