/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * InlineResponse200Results
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-10T18:36:59.050+01:00")
public class InlineResponse200Results   {
  @SerializedName("datafile")
  private String datafile = null;

  @SerializedName("used")
  private Boolean used = null;

  @SerializedName("parameters")
  private String parameters = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("inerror")
  private Boolean inerror = null;

  @SerializedName("parametersresult")
  private String parametersresult = null;

  @SerializedName("errorcode")
  private String errorcode = null;

  @SerializedName("processed_date")
  private String processedDate = null;

  @SerializedName("processed")
  private Boolean processed = null;

  @SerializedName("id")
  private String id = null;

  public InlineResponse200Results datafile(String datafile) {
    this.datafile = datafile;
    return this;
  }

   /**
   * If needed, file to be processed by the accelerator.
   * @return datafile
  **/
  @ApiModelProperty(example = "null", value = "If needed, file to be processed by the accelerator.")
  public String getDatafile() {
    return datafile;
  }

  public void setDatafile(String datafile) {
    this.datafile = datafile;
  }

  public InlineResponse200Results used(Boolean used) {
    this.used = used;
    return this;
  }

   /**
   * 
   * @return used
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUsed() {
    return used;
  }

  public void setUsed(Boolean used) {
    this.used = used;
  }

  public InlineResponse200Results parameters(String parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * All parameters need for the excution in JSON format : {     \"AcceleratorParam1\":\"value1\",    \"AcceleratorParam2\":\"value2\",    \"AcceleratorParam3\":\"value3\"}
   * @return parameters
  **/
  @ApiModelProperty(example = "null", value = "All parameters need for the excution in JSON format : {     \"AcceleratorParam1\":\"value1\",    \"AcceleratorParam2\":\"value2\",    \"AcceleratorParam3\":\"value3\"}")
  public String getParameters() {
    return parameters;
  }

  public void setParameters(String parameters) {
    this.parameters = parameters;
  }

  public InlineResponse200Results created(String created) {
    this.created = created;
    return this;
  }

   /**
   * 
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public InlineResponse200Results url(String url) {
    this.url = url;
    return this;
  }

   /**
   * 
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public InlineResponse200Results inerror(Boolean inerror) {
    this.inerror = inerror;
    return this;
  }

   /**
   * 
   * @return inerror
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getInerror() {
    return inerror;
  }

  public void setInerror(Boolean inerror) {
    this.inerror = inerror;
  }

  public InlineResponse200Results parametersresult(String parametersresult) {
    this.parametersresult = parametersresult;
    return this;
  }

   /**
   * 
   * @return parametersresult
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParametersresult() {
    return parametersresult;
  }

  public void setParametersresult(String parametersresult) {
    this.parametersresult = parametersresult;
  }

  public InlineResponse200Results errorcode(String errorcode) {
    this.errorcode = errorcode;
    return this;
  }

   /**
   * 
   * @return errorcode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getErrorcode() {
    return errorcode;
  }

  public void setErrorcode(String errorcode) {
    this.errorcode = errorcode;
  }

  public InlineResponse200Results processedDate(String processedDate) {
    this.processedDate = processedDate;
    return this;
  }

   /**
   * 
   * @return processedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProcessedDate() {
    return processedDate;
  }

  public void setProcessedDate(String processedDate) {
    this.processedDate = processedDate;
  }

  public InlineResponse200Results processed(Boolean processed) {
    this.processed = processed;
    return this;
  }

   /**
   * 
   * @return processed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getProcessed() {
    return processed;
  }

  public void setProcessed(Boolean processed) {
    this.processed = processed;
  }

  public InlineResponse200Results id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Results inlineResponse200Results = (InlineResponse200Results) o;
    return Objects.equals(this.datafile, inlineResponse200Results.datafile) &&
        Objects.equals(this.used, inlineResponse200Results.used) &&
        Objects.equals(this.parameters, inlineResponse200Results.parameters) &&
        Objects.equals(this.created, inlineResponse200Results.created) &&
        Objects.equals(this.url, inlineResponse200Results.url) &&
        Objects.equals(this.inerror, inlineResponse200Results.inerror) &&
        Objects.equals(this.parametersresult, inlineResponse200Results.parametersresult) &&
        Objects.equals(this.errorcode, inlineResponse200Results.errorcode) &&
        Objects.equals(this.processedDate, inlineResponse200Results.processedDate) &&
        Objects.equals(this.processed, inlineResponse200Results.processed) &&
        Objects.equals(this.id, inlineResponse200Results.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datafile, used, parameters, created, url, inerror, parametersresult, errorcode, processedDate, processed, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Results {\n");
    
    sb.append("    datafile: ").append(toIndentedString(datafile)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    inerror: ").append(toIndentedString(inerror)).append("\n");
    sb.append("    parametersresult: ").append(toIndentedString(parametersresult)).append("\n");
    sb.append("    errorcode: ").append(toIndentedString(errorcode)).append("\n");
    sb.append("    processedDate: ").append(toIndentedString(processedDate)).append("\n");
    sb.append("    processed: ").append(toIndentedString(processed)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

