/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse200Results;
import java.util.ArrayList;
import java.util.List;


/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-10T18:36:59.050+01:00")
public class InlineResponse200   {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("previous")
  private String previous = null;

  @SerializedName("results")
  private List<InlineResponse200Results> results = new ArrayList<InlineResponse200Results>();

  @SerializedName("next")
  private String next = null;

  public InlineResponse200 count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * 
   * @return count
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public InlineResponse200 previous(String previous) {
    this.previous = previous;
    return this;
  }

   /**
   * 
   * @return previous
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPrevious() {
    return previous;
  }

  public void setPrevious(String previous) {
    this.previous = previous;
  }

  public InlineResponse200 results(List<InlineResponse200Results> results) {
    this.results = results;
    return this;
  }

  public InlineResponse200 addResultsItem(InlineResponse200Results resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * 
   * @return results
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<InlineResponse200Results> getResults() {
    return results;
  }

  public void setResults(List<InlineResponse200Results> results) {
    this.results = results;
  }

  public InlineResponse200 next(String next) {
    this.next = next;
    return this;
  }

   /**
   * 
   * @return next
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.count, inlineResponse200.count) &&
        Objects.equals(this.previous, inlineResponse200.previous) &&
        Objects.equals(this.results, inlineResponse200.results) &&
        Objects.equals(this.next, inlineResponse200.next);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, previous, results, next);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

