/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * InlineResponse2004
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-10T18:36:59.050+01:00")
public class InlineResponse2004   {
  @SerializedName("datafile")
  private String datafile = null;

  @SerializedName("parameters")
  private String parameters = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("inerror")
  private Boolean inerror = null;

  @SerializedName("parametersresult")
  private String parametersresult = null;

  @SerializedName("errorcode")
  private String errorcode = null;

  @SerializedName("processed_date")
  private String processedDate = null;

  @SerializedName("datafileresult")
  private String datafileresult = null;

  @SerializedName("processed")
  private Boolean processed = null;

  @SerializedName("configuration")
  private String _configuration = null;

  @SerializedName("id")
  private String id = null;

  public InlineResponse2004 datafile(String datafile) {
    this.datafile = datafile;
    return this;
  }

   /**
   * If needed, file to be processed by the accelerator.
   * @return datafile
  **/
  @ApiModelProperty(example = "null", value = "If needed, file to be processed by the accelerator.")
  public String getDatafile() {
    return datafile;
  }

  public void setDatafile(String datafile) {
    this.datafile = datafile;
  }

  public InlineResponse2004 parameters(String parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * All parameters need for the excution in JSON format : {     \"AcceleratorParam1\":\"value1\",    \"AcceleratorParam2\":\"value2\",    \"AcceleratorParam3\":\"value3\"}
   * @return parameters
  **/
  @ApiModelProperty(example = "null", value = "All parameters need for the excution in JSON format : {     \"AcceleratorParam1\":\"value1\",    \"AcceleratorParam2\":\"value2\",    \"AcceleratorParam3\":\"value3\"}")
  public String getParameters() {
    return parameters;
  }

  public void setParameters(String parameters) {
    this.parameters = parameters;
  }

  public InlineResponse2004 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * 
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public InlineResponse2004 inerror(Boolean inerror) {
    this.inerror = inerror;
    return this;
  }

   /**
   * 
   * @return inerror
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getInerror() {
    return inerror;
  }

  public void setInerror(Boolean inerror) {
    this.inerror = inerror;
  }

  public InlineResponse2004 parametersresult(String parametersresult) {
    this.parametersresult = parametersresult;
    return this;
  }

   /**
   * 
   * @return parametersresult
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParametersresult() {
    return parametersresult;
  }

  public void setParametersresult(String parametersresult) {
    this.parametersresult = parametersresult;
  }

  public InlineResponse2004 errorcode(String errorcode) {
    this.errorcode = errorcode;
    return this;
  }

   /**
   * 
   * @return errorcode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getErrorcode() {
    return errorcode;
  }

  public void setErrorcode(String errorcode) {
    this.errorcode = errorcode;
  }

  public InlineResponse2004 processedDate(String processedDate) {
    this.processedDate = processedDate;
    return this;
  }

   /**
   * 
   * @return processedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProcessedDate() {
    return processedDate;
  }

  public void setProcessedDate(String processedDate) {
    this.processedDate = processedDate;
  }

  public InlineResponse2004 datafileresult(String datafileresult) {
    this.datafileresult = datafileresult;
    return this;
  }

   /**
   * If needed, file  processed by the accelerator.
   * @return datafileresult
  **/
  @ApiModelProperty(example = "null", value = "If needed, file  processed by the accelerator.")
  public String getDatafileresult() {
    return datafileresult;
  }

  public void setDatafileresult(String datafileresult) {
    this.datafileresult = datafileresult;
  }

  public InlineResponse2004 processed(Boolean processed) {
    this.processed = processed;
    return this;
  }

   /**
   * 
   * @return processed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getProcessed() {
    return processed;
  }

  public void setProcessed(Boolean processed) {
    this.processed = processed;
  }

  public InlineResponse2004 _configuration(String _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Id of the configuration to use for this process
   * @return _configuration
  **/
  @ApiModelProperty(example = "null", required = true, value = "Id of the configuration to use for this process")
  public String getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(String _configuration) {
    this._configuration = _configuration;
  }

  public InlineResponse2004 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.datafile, inlineResponse2004.datafile) &&
        Objects.equals(this.parameters, inlineResponse2004.parameters) &&
        Objects.equals(this.url, inlineResponse2004.url) &&
        Objects.equals(this.inerror, inlineResponse2004.inerror) &&
        Objects.equals(this.parametersresult, inlineResponse2004.parametersresult) &&
        Objects.equals(this.errorcode, inlineResponse2004.errorcode) &&
        Objects.equals(this.processedDate, inlineResponse2004.processedDate) &&
        Objects.equals(this.datafileresult, inlineResponse2004.datafileresult) &&
        Objects.equals(this.processed, inlineResponse2004.processed) &&
        Objects.equals(this._configuration, inlineResponse2004._configuration) &&
        Objects.equals(this.id, inlineResponse2004.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datafile, parameters, url, inerror, parametersresult, errorcode, processedDate, datafileresult, processed, _configuration, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    datafile: ").append(toIndentedString(datafile)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    inerror: ").append(toIndentedString(inerror)).append("\n");
    sb.append("    parametersresult: ").append(toIndentedString(parametersresult)).append("\n");
    sb.append("    errorcode: ").append(toIndentedString(errorcode)).append("\n");
    sb.append("    processedDate: ").append(toIndentedString(processedDate)).append("\n");
    sb.append("    datafileresult: ").append(toIndentedString(datafileresult)).append("\n");
    sb.append("    processed: ").append(toIndentedString(processed)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

