/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-10T18:36:59.050+01:00")
public class InlineResponse2001   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("inerror")
  private Boolean inerror = null;

  @SerializedName("processed_date")
  private String processedDate = null;

  @SerializedName("parametersresult")
  private String parametersresult = null;

  @SerializedName("errorcode")
  private String errorcode = null;

  @SerializedName("processed")
  private Boolean processed = null;

  public InlineResponse2001 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse2001 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * 
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public InlineResponse2001 inerror(Boolean inerror) {
    this.inerror = inerror;
    return this;
  }

   /**
   * 
   * @return inerror
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getInerror() {
    return inerror;
  }

  public void setInerror(Boolean inerror) {
    this.inerror = inerror;
  }

  public InlineResponse2001 processedDate(String processedDate) {
    this.processedDate = processedDate;
    return this;
  }

   /**
   * 
   * @return processedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProcessedDate() {
    return processedDate;
  }

  public void setProcessedDate(String processedDate) {
    this.processedDate = processedDate;
  }

  public InlineResponse2001 parametersresult(String parametersresult) {
    this.parametersresult = parametersresult;
    return this;
  }

   /**
   * 
   * @return parametersresult
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParametersresult() {
    return parametersresult;
  }

  public void setParametersresult(String parametersresult) {
    this.parametersresult = parametersresult;
  }

  public InlineResponse2001 errorcode(String errorcode) {
    this.errorcode = errorcode;
    return this;
  }

   /**
   * 
   * @return errorcode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getErrorcode() {
    return errorcode;
  }

  public void setErrorcode(String errorcode) {
    this.errorcode = errorcode;
  }

  public InlineResponse2001 processed(Boolean processed) {
    this.processed = processed;
    return this;
  }

   /**
   * 
   * @return processed
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getProcessed() {
    return processed;
  }

  public void setProcessed(Boolean processed) {
    this.processed = processed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.id, inlineResponse2001.id) &&
        Objects.equals(this.url, inlineResponse2001.url) &&
        Objects.equals(this.inerror, inlineResponse2001.inerror) &&
        Objects.equals(this.processedDate, inlineResponse2001.processedDate) &&
        Objects.equals(this.parametersresult, inlineResponse2001.parametersresult) &&
        Objects.equals(this.errorcode, inlineResponse2001.errorcode) &&
        Objects.equals(this.processed, inlineResponse2001.processed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, inerror, processedDate, parametersresult, errorcode, processed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    inerror: ").append(toIndentedString(inerror)).append("\n");
    sb.append("    processedDate: ").append(toIndentedString(processedDate)).append("\n");
    sb.append("    parametersresult: ").append(toIndentedString(parametersresult)).append("\n");
    sb.append("    errorcode: ").append(toIndentedString(errorcode)).append("\n");
    sb.append("    processed: ").append(toIndentedString(processed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

