/**
 * Accelize Accelerator WS
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package accelize_accelerator;

import invalidPackageName.ApiException;
import io.swagger.client.model.InlineResponse2001;
import java.io.File;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigurationApi
 */
public class ConfigurationApiTest {

    private final ConfigurationApi api = new ConfigurationApi();

    
    /**
     * /v1.0/configuration/
     *
     * Create a new configuration instance and deploy it.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configurationCreateTest() throws ApiException {
        String owner = null;
        String provider = null;
        String parameters = null;
        File datafile = null;
        // InlineResponse2001 response = api.configurationCreate(owner, provider, parameters, datafile);

        // TODO: test validations
    }
    
    /**
     * /v1.0/configuration/
     *
     * Returns a list of all accelerator configuration instance requested in the system.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configurationListTest() throws ApiException {
        Integer page = null;
        // InlineResponse200 response = api.configurationList(page);

        // TODO: test validations
    }
    
    /**
     * /v1.0/configuration/{id}/
     *
     * Return the given configuration instance.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void configurationReadTest() throws ApiException {
        Integer id = null;
        // InlineResponse2002 response = api.configurationRead(id);

        // TODO: test validations
    }
    
}
